name: pytest

on: [pull_request]

jobs:
  test:
    # only run if triggering branch is not main
    if: ${{github.ref_name != 'main'}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , windows-latest] , macos-latest]
        python-version: [3.11]

    runs-on: ${{ matrix.os }}

    name: Test ${{ matrix.os }} + Py ${{ matrix.python-version }} + ${{ github.ref }} + ${{github.base_ref}}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: pip install poetry
    - name: Get packages via poetry
      run: poetry install

    - name: Install playwright
      run: |
        poetry run python -m playwright install chrome
        ls

    - name: Unit tests with pytest
      run: |
        poetry run python -m pytest tests/ --log-cli-level=debug